### ISSUE TITLE
HomePlus Pro

### ISSUE THREAD

**Issue by kenstrife** [KritantaDev/HomePlus#11]
horizontal & vertical spacing on dock is not working. even the column. i’m using iphone 6s 13.5 uncover

**Comment by Nicklasfox** [comment]
Have you tried to respring the device? Still Problem?

**Comment by kenstrife** [comment]
> Have you tried to respring the device? Still Problem?

yes even ldrestart and uninstall and reinstall. still same problem.

**Comment by kenstrife** [comment]
it's fixed on latest version. thanks
